### ISSUE TITLE
To `ToString(string)` or not to `ToString(string)`?

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/proposal-number-fromstring#17]
Step 1 of both algorithms is:

```
1. Let _S_ be ? ToString(_string_).
```

As @jakobkummerow points out, we could choose to not do this, and instead just throw for non-string arguments.

**Comment by jakobkummerow** [comment]
Obviously, a large number of existing functions in ECMAScript perform various implicit conversions on their arguments. `.fromString` could choose to match that pattern.

That said, there is also a large number of existing cases of TypeErrors being thrown for invalid arguments to various functions.

From a "minimizing surprise" point of view, given that the thing is called "from**String**", being required to pass a string to it seems less surprising than being able to pass arbitrary objects. (`Number.parseInt(true, 32) === 978894` seems quite surprising -- `Number.fromString` should preserve more sanity!)

FWIW, implementation effort and execution speed (when passing strings) should be pretty much the same.
