### ISSUE TITLE
Number.fromString does not parse all number strings

### ISSUE THREAD

**Issue by domenic** [mathiasbynens/proposal-number-fromstring#6]
In particular, `Number.fromString(123.456.toString())` produces `123` (or would produce an error if #5 was implemented). I'd expect `123.456`.

**Comment by mathiasbynens** [comment]
a29f339980abb55d93f50c650294eedf071363d5 includes this change — compare step 9 in both algorithms. Please take a look and let me know of any issues.

**Comment by JTBrinkmann** [comment]
This proposal's motivation is stated to offer a way to invert `{BigInt,Number}.prototype.toString(radix)`, yet the specs and README only focus on integers, despite `Number.prototype.toString(radix)` potentially returning string representation of non-integer numbers.

a29f339 does **not** "include this change", instead it causes a SyntaxError to be thrown.

> I'd expect `123.456`
