### ISSUE TITLE
What does a radix of 0 mean?

### ISSUE THREAD

**Issue by domenic** [mathiasbynens/proposal-number-fromstring#7]
The readme says

> fromString throws a RangeError exception when radix !== 0 && radix < 2 or radix > 36.

What does a radix of 0 mean? I don't think it has any mathematical meaning.

Note that Number.prototype.toString() throws for a radix of 0. Being symmetric with that seems better.

**Comment by mathiasbynens** [comment]
If `radix` is 0 or `undefined`, it is currently set to 10 (matching `parseInt`). I agree it makes more sense to disallow it for this new feature.

**Comment by mathiasbynens** [comment]
a29f339980abb55d93f50c650294eedf071363d5 includes this change. Please take a look and let me know of any issues.
