### ISSUE TITLE
Consider not allowing leading whitespace

### ISSUE THREAD

**Issue by domenic** [mathiasbynens/proposal-number-fromstring#9]
The treatment of the beginning and end of the string is asymmetric; the beginning allows leading whitespace, while (#5) the end allows any trailing characters. This is weird.

I think the best thing to do, which also fits with the inverse-of-Number.prototype.toString idea, is to disallow both.

**Comment by littledan** [comment]
Symmetrical treatment sounds good. I'd be fine with allowing both as well (as the BigInt constructor does).

**Comment by mathiasbynens** [comment]
a29f339980abb55d93f50c650294eedf071363d5 includes this change. Please take a look and let me know of any issues.
